apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iperf-test

resources:
  - ../../base
  - hello-world-deployment.yaml
  - hello-world-service.yaml
  - iperf3-perf-job.yaml
  - wrk-perf-job.yaml

configMapGenerator:
  - name: wrk-scripts
    files:
      - report.lua=wrk-report.lua

generatorOptions:
  disableNameSuffixHash: true
