apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
  namespace: iperf-test
spec:
  selector:
    app: iperf3-server
  ports:
    - name: iperf3
      protocol: TCP
      port: 5201
      targetPort: 5201
    - name: iperf3-udp
      protocol: UDP
      port: 5201
      targetPort: 5201
  type: ClusterIP
