apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cni-np-test

resources:
  - namespace.yaml
  - np-results-git-configmap.yaml
  - demo-app-frontend.yaml
  - demo-app-backend.yaml
  - demo-app-database.yaml
  - iperf-server-np.yaml
  - iperf-client-np-cronjob.yaml
  - latency-client-np-cronjob.yaml
