apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - iperf3-performance-job.yaml

configMapGenerator:
  - name: iperf3-test-script
    files:
      - iperf-test.sh

generatorOptions:
  disableNameSuffixHash: true
