apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cni-np-test

resources:
  - ../../../base
  - ../../../use-case-2-multi-tier
  # CiliumNetworkPolicy L7: diferenciador exclusivo de Cilium (filtrado HTTP)
  - cilium-l7-policy.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cni-np-results-git-config
      data:
        CNI_NAME: "cilium"
        NP_CASE: "multi_tier"
    target:
      kind: ConfigMap
      name: cni-np-results-git-config
