apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../cni_test_iperf

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cni-results-git-config
      data:
        CNI_NAME: "cilium"
    target:
      kind: ConfigMap
      name: cni-results-git-config
