apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cni-test

resources:
  - namespace.yaml
  - iperf-server.yaml
  - iperf-client-cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: cni-test
  app.kubernetes.io/managed-by: argocd
