apiVersion: v1
kind: Namespace
metadata:
  name: cni-test
  annotations:
    # ArgoCD: crear el Namespace antes que cualquier recurso namespaced
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: cni-test
    purpose: network-benchmark
