apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cni-np-test

resources:
  - np-allow-dns.yaml
  - np-allow-internal.yaml
  - np-block-external-egress.yaml
  - np-allow-benchmark.yaml
