apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cni-np-test

resources:
  - ../../../base
  - ../../../use-case-1-zero-trust

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cni-np-results-git-config
      data:
        CNI_NAME: "calico"
        NP_CASE: "zero_trust"
    target:
      kind: ConfigMap
      name: cni-np-results-git-config
